// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IDataSource.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Agenda_AgendaDS interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IAgenda_AgendaDS
    {
		Task<ObservableCollection<Entities.AgendaDSSchema>> GetData(int pageNumber = 0);
        Task<ObservableCollection<Entities.AgendaDSSchema>> Refresh();
		Task<ObservableCollection<Entities.AgendaDSSchema>> Search(FilterSpecification filter);
		Entities.AgendaDSSchema Previous(Entities.AgendaDSSchema current);
		Task<Entities.AgendaDSSchema> Next(Entities.AgendaDSSchema current);
    }
}
