// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IDataSource.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Speakers_SpeakersDS interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ISpeakers_SpeakersDS
    {
		Task<ObservableCollection<Entities.SpeakersDSSchema>> GetData(int pageNumber = 0);
        Task<ObservableCollection<Entities.SpeakersDSSchema>> Refresh();
		Task<ObservableCollection<Entities.SpeakersDSSchema>> Search(FilterSpecification filter);
		Entities.SpeakersDSSchema Previous(Entities.SpeakersDSSchema current);
		Task<Entities.SpeakersDSSchema> Next(Entities.SpeakersDSSchema current);
    }
}
