// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	DataSource.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities = WPAppStudio.Entities;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// HomeDS_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Home_HomeDS : IHome_HomeDS 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<b>KOCHI DEVCON 2014</b> will help you to engage and collaborate with Microsoft
 MVPs and thousands of your developer peers, building connections,
                    learn about the Microsoft’s cutting edge 
technologies from the industry experts. Sessions on Cloud, Microsoft and Mobile technologies.<br /><br /><b>VENUE </b>: InfoPark Hall, Athulya Cafeterial Block, Kakkanad , Kochi<br /><b>DATE </b>: Saturday, 15 February 2014<br /><br /><b>K-MUG</b> is one of the most successful technical community in India, which focus on Microsoft Technologies. Participation in K-MUG
 is an excellent, inexpensive way to receive technical content, 
education and to meet with peers to get more out of the Microsoft 
platforms, products, technologies, and resources<br /><br />";
        }
	}
}

