// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	DataSource.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities = WPAppStudio.Entities;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// AppChallengeDS_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class WPAppChallenge_AppChallengeDS : IWPAppChallenge_AppChallengeDS 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"Create a cool windows phone app and present it on stage, using 
Windows Phone Emulator / actual device. Each participants will get 5 
minutes to demonstrate their app, and judges will select the top 3 
apps.We will help the winners to submit their apps to Windows phone 
store, and winners enjoy the cool Nokia Lumia phones ;)
							Apps will be judged based on the criteria below and weighted 
accordingly.<br /><br />
							<strong>33% Weight – User Experience</strong><br />
							<strong>33% Weight - Innovation &amp;amp; Originality of idea</strong><br />
							<strong>33% Weight - Technical creativity</strong><br />
							<br />
                                Please send your app nomination with app name and description to <a title=""Link: null"" target=""_blank"" rel=""nofollow"">admin@k-mug.org</a>
 by 14th feb 8pm (ist). on 15th, our screening committee will evaluate 
all the apps before the lunch break, and the top 6 apps will be 
evaluated by judges during after noon session.<br />";
        }
	}
}

