// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Home_Info ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IHome_InfoViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentHome_InfoHtmlControl property.
        /// </summary>
		string CurrentHome_InfoHtmlControl { get; set; }
        /// <summary>
        /// Gets/Sets the Agenda_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.AgendaDSSchema> Agenda_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Agenda_ListListControlCollectionPageNumber property.
        /// </summary>
		int Agenda_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedAgenda_ListListControlCollection property.
        /// </summary>
		Entities.AgendaDSSchema SelectedAgenda_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Speakers_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.SpeakersDSSchema> Speakers_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Speakers_ListListControlCollectionPageNumber property.
        /// </summary>
		int Speakers_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedSpeakers_ListListControlCollection property.
        /// </summary>
		Entities.SpeakersDSSchema SelectedSpeakers_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the CurrentWPAppChallenge_InfoHtmlControl property.
        /// </summary>
		string CurrentWPAppChallenge_InfoHtmlControl { get; set; }
        /// <summary>
        /// Gets/Sets the Sponsors_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.SponsorsDSSchema> Sponsors_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Sponsors_ListListControlCollectionPageNumber property.
        /// </summary>
		int Sponsors_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedSponsors_ListListControlCollection property.
        /// </summary>
		Entities.SponsorsDSSchema SelectedSponsors_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the RefreshAgenda_ListListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshAgenda_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetAgenda_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetAgenda_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the RefreshSpeakers_ListListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshSpeakers_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetSpeakers_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetSpeakers_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the RefreshSponsors_ListListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshSponsors_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetSponsors_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetSponsors_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechHome_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechHome_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareHome_InfoHtmlControlCommand command.
        /// </summary>
		ICommand ShareHome_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartHome_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartHome_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechWPAppChallenge_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechWPAppChallenge_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareWPAppChallenge_InfoHtmlControlCommand command.
        /// </summary>
		ICommand ShareWPAppChallenge_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartWPAppChallenge_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartWPAppChallenge_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
