// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Speakers_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ISpeakers_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentSpeakersDSSchema property.
        /// </summary>
		Entities.SpeakersDSSchema CurrentSpeakersDSSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaSpeakers_Detail0 property.
        /// </summary>
		bool HasNextpanoramaSpeakers_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaSpeakers_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaSpeakers_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechSpeakers_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechSpeakers_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareSpeakers_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareSpeakers_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartSpeakers_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartSpeakers_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaSpeakers_Detail0 command.
        /// </summary>
		ICommand NextpanoramaSpeakers_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaSpeakers_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaSpeakers_Detail0 { get; }

	}
}
